CC	= gcc
SRC	= src/
CFLAGS  = -O -Wall -Wno-pointer-sign -ggdb
LIBS    = -lm  -L/usr/local/ssl/lib -lssl -lcrypto   
INCLUDE = -I./src/ -I. -I/usr/local/ssl/include  -Isrc/c-ares 
OBJS	= src/psybnc.o src/match.o src/p_client.o src/p_crypt.o src/p_dcc.o src/p_hash.o src/p_idea.o src/p_inifunc.o src/p_link.o src/p_log.o src/p_memory.o src/p_network.o src/p_parse.o src/p_peer.o src/p_server.o src/p_socket.o src/p_string.o src/p_sysmsg.o src/p_userfile.o src/p_uchannel.o src/p_script.o src/p_topology.o src/p_intnet.o src/p_blowfish.o src/p_translate.o src/snprintf.o src/p_dns.o 
DEFINE	= -DHAVE_CONFIG -DBIGENDIAN -DIPV6  -DNOSYSTIME -DHAVE_SSL 
TARGET	= psybnc

all:	$(OBJS)
	$(CC) -o $(TARGET) $(CFLAGS) $(OBJS) src/c-ares/.libs/libcares.a  $(LIBS)

	@echo
	@echo psyBNC2.4-BETA1-Linux ready. Please read the README before you run psybnc.

	@echo
include ./targets.mak
